--- !ditz.rubyforge.org,2008-03-06/project 
name: whatsnewfm
version: "0.5"
components: 
- !ditz.rubyforge.org,2008-03-06/component 
  name: whatsnewfm
releases: 
- !ditz.rubyforge.org,2008-03-06/release 
  name: 0.7.1
  status: :unreleased
  release_time: 
  log_events: 
  - - 2009-03-29 08:53:45.253095 Z
    - Christian Garbs <mitch@cgarbs.de>
    - created
    - ""
- !ditz.rubyforge.org,2008-03-06/release 
  name: 0.7.2
  status: :unreleased
  release_time: 
  log_events: 
  - - 2009-05-30 19:39:59.697675 Z
    - Christian Garbs <mitch@cgarbs.de>
    - created
    - ""
